server:
    port: 8080

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    datasource:
        driverClassName: oracle.jdbc.OracleDriver
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        url: jdbc:oracle:thin:@......
        databaseName: 
        serverName: 
        username: XXXXX
        password: YYYYY

    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        database: ORACLE
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: huborcid


